project:
  type: website

website:
  title: "Things with Maps"
  repo-url: https://github.com/MattBixley/condes_tutorial
  issue-url: https://github.com/MattBixley/condes_tutorial/issues
  repo-actions: edit
  back-to-top-navigation: true
    
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: pages/condes_tutorial.qmd
        text: Condes Tutorial
      - href: pages/course_planning.qmd
        text: Course Planning
      - href: pages/rogaine_planning.qmd
        text: Rogaine Planning
    right:
      - icon: github
        href: https://github.com/MattBixley/condes_tutorial
        aria-label: GitHub    
        
format:
  html:
    theme: sketchy
    css: styles.css
    

editor: visual

