project:
  type: website

website:
  title: "condes_tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- about.qmd
      - href: contact.qmd
        text: Contact
    

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

